version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_DATABASE: boutiqueParfum 
    ports:
      - "3307:3306"                   
    volumes:
      - mysql-data:/var/lib/mysql     
    networks:
      - spring-boot-network

networks:
  spring-boot-network:

volumes:
  mysql-data:
